### ISSUE TITLE
Missing requirements in documentation

### ISSUE THREAD

**Issue by chrismyers81** [mozilla-services/syncserver#103]
When I went to install this on Debian Stretch, there are a couple of additional packages (and their requirements) that I needed to install, in addition to those mentioned in the documentation.

When building, I encountered this error:

> gcc: error trying to exec 'cc1plus': execvp: No such file or directory

To solve it, I needed to install gcc (and its corequisites)

After doing a clean and build following that installation, I encountered the error:

> gcc: error trying to exec 'cc1plus': execvp: No such file or directory

To solve that message, I had to install g++.

After doing those two additional ones, I was able to build successfully.

**Comment by rfk** [comment]
Thanks @chrismyers81.  These dependencies are mentioned in https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html#prerequisites but looks like they're not in the readme here.  I've added them in https://github.com/mozilla-services/syncserver/commit/3d81c658f259b3785c9914bfbf71b4b1d0615bb0
