### ISSUE TITLE
Introduce tags on docker hub

### ISSUE THREAD

**Issue by schnatterer** [mozilla-services/syncserver#109]
I just synced successfully to a docker container started from the image `mozilla/syncserver:latest` (published 4 days ago) from docker hub. Thanks for your work, guys!

The whole process would be more deterministic if you used tags at docker hub, so users can refer to defined versions when starting container from images, instead of `latest` (which is subject to change).

**Comment by rfk** [comment]
I'm glad to hear ithe docker image worked, and thanks for the suggestion.  It's likely dependent on us actually starting to tag releases in this repo, which I haven't been doing a thorough job of.  I'm going to add one now and see whether the docker pipeline picks it up...

**Comment by rfk** [comment]
Looks like that pushed the tag to docker automatically \o/

  https://hub.docker.com/r/mozilla/syncserver/tags/

**Comment by schnatterer** [comment]
Hey @rfk, thanks for tag!
I can confirm that syncing still works with `mozilla/syncserver:v1.7.0`.
