### ISSUE TITLE
syncserver storage error

### ISSUE THREAD

**Issue by snIP3r23** [mozilla-services/syncserver#140]
hi all!
after recovering my working installation of syncserver i now cannot get it working again. in my apace logs i get theses messages:
error_log:
`[Fri Sep 28 20:25:09.940481 2018] [wsgi:error] [pid 4910] [remote 217.235.72.198:50308] WARNING:syncstorage.views.authentication:Authentication Failed: invalid hawk id`
access_log:
`217.235.66.61 - - [30/Sep/2018:12:51:06 +0200] "GET /token/1.0/sync/1.5 HTTP/1.1" 200 521
217.235.66.61 - - [30/Sep/2018:12:51:06 +0200] "GET /storage/1.5/1/info/collections HTTP/1.1" 401 1
217.235.66.61 - - [30/Sep/2018:12:51:06 +0200] "GET /token/1.0/sync/1.5 HTTP/1.1" 200 521
`
in /var/log/apache2/ssl_error_log:
`[Fri Sep 28 20:25:09.940481 2018] [wsgi:error] [pid 4910] [remote 217.235.72.198:50308] WARNING:syncstorage.views.authentication:Authentication Faile
d: invalid hawk id`

in sync log of firefox:
`1538158770071	Sync.LogManager	DEBUG	Flushing file log
1538158770080	Sync.LogManager	DEBUG	Log cleanup threshold time: 1537294770080
1538158770094	Sync.LogManager	DEBUG	Done deleting files.
1538158771570	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://profile.accounts.firefox.com/v1/profile
1538158771570	Services.Common.RESTRequest	TRACE	Channel for GET https://profile.accounts.firefox.com/v1/profile returned status code 0
1538158771570	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1538158771570	Services.Common.RESTRequest	TRACE	GET body: 
1538159107546	Sync.Service	DEBUG	User-Agent: Firefox/62.0.2 (Windows NT 10.0; Win64; x64) FxSync/1.64.0.20180920131237.desktop
1538159107546	Sync.Service	INFO	Starting sync at 2018-09-28 20:25:07 in browser session ZiYq54onf_5V
1538159107546	Sync.Service	DEBUG	In sync: should login.
1538159107546	Sync.Service	INFO	User logged in successfully - verifying login.
1538159107547	Sync.BrowserIDManager	DEBUG	unlockAndVerifyAuthState already has (or can fetch) sync keys
1538159107547	Sync.Status	DEBUG	Status.login: error.login.reason.network => success.status_ok
1538159107547	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1538159107547	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1538159107547	Sync.BrowserIDManager	INFO	Getting keys
1538159107548	Sync.BrowserIDManager	INFO	Getting an assertion from: https://SERVER/token/1.0/sync/1.5
1538159107548	FirefoxAccounts	DEBUG	enter getAssertion()
1538159107548	FirefoxAccounts	DEBUG	getKeypairAndCertificate: already have keyPair and certificate
1538159107548	FirefoxAccounts	DEBUG	getAssertionFromCert
1538159107549	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1538159107549	Sync.BrowserIDManager	DEBUG	Getting a token
1538159107549	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://SERVER/token/1.0/sync/1.5
1538159107549	Services.Common.RESTRequest	DEBUG	GET request to https://SERVER/token/1.0/sync/1.5
1538159107549	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1538159107549	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1538159107549	Services.Common.RESTRequest	TRACE	HTTP Header x-client-state: cdc794b9bd26b64f527f2387158874a2
1538159107605	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://SERVER/token/1.0/sync/1.5
1538159107605	Services.Common.RESTRequest	TRACE	Channel for GET https://SERVER/token/1.0/sync/1.5 returned status code 0
1538159107605	Services.Common.RESTRequest	DEBUG	GET https://SERVER/token/1.0/sync/1.5 200
1538159107605	Services.Common.RESTRequest	TRACE	GET body: {"uid": 1, "hashalg": "sha256", "api_endpoint": "https://SERVER/storage/1.5/1", "duration": 300, "key": "PZ4Q39PDHSV3Sei8aXfVvmwB1bvdAp_hL8VimFBmf2Q=", "hashed_fxa_uid": "ID", "id": "eyJub2RlIjogImh0dHBzOi8vZnMuYXJlYTUyLmRuc2hvbWUuZGUiLCAidWlkIjogMSwgImV4cGlyZXMiOiAxNTM4MTU5NDA5LCAiZnhhX3VpZCI6ICIwM2VmZDIwODhlNTY4YzI1ZGE0ZDFjNGY0Yjg4NzFjOSIsICJzYWx0IjogIjgzZjEzMCIsICJkZXZpY2VfaWQiOiAiNDY4YWI3ZGRjMmNhZjZhYjNkOWMzMjRjNGU5N2NiMjkifXxhUnipQUM8rGeCmC0lheLI-uWPDFz9lWItbeVojZBL"}
1538159107605	Services.Common.TokenServerClient	DEBUG	Got token response: 200
1538159107605	Services.Common.RESTResponse	TRACE	Processing response headers.
1538159107605	Services.Common.TokenServerClient	DEBUG	Successful token response
1538159107605	Sync.Status	DEBUG	Status.login: success.status_ok => success.login
1538159107605	Sync.Status	DEBUG	Status.service: error.login.failed => success.status_ok
1538159107607	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1538159107607	FirefoxAccounts	DEBUG	getOAuthToken enter
1538159107607	FirefoxAccounts	TRACE	getCachedToken returning cached token
1538159107607	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1538159107607	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1538159107607	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1538159107607	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1538159107607	Services.Common.RESTRequest	TRACE	HTTP Header if-none-match: "3f0d91e7170f4a0b726f7f8cb4b73690e425fc26-gzip"
1538159107616	Sync.Resource	DEBUG	GET fail 401 https://SERVER/storage/1.5/1/info/collections
1538159107616	Sync.Resource	WARN	GET request to https://SERVER/storage/1.5/1/info/collections failed with status 401
1538159107616	Sync.Service	WARN	401: login failed.
1538159107616	Sync.BrowserIDManager	DEBUG	_findCluster has a pre-existing clusterURL, so fetching a new token token
1538159107617	Sync.BrowserIDManager	INFO	Getting keys
1538159107617	Sync.BrowserIDManager	INFO	Getting an assertion from: https://SERVER/token/1.0/sync/1.5
1538159107617	FirefoxAccounts	DEBUG	enter getAssertion()
1538159107617	FirefoxAccounts	DEBUG	getKeypairAndCertificate: already have keyPair and certificate
1538159107617	FirefoxAccounts	DEBUG	getAssertionFromCert
1538159107619	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1538159107619	Sync.BrowserIDManager	DEBUG	Getting a token
1538159107619	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://SERVER/token/1.0/sync/1.5
1538159107619	Services.Common.RESTRequest	DEBUG	GET request to https://SERVER/token/1.0/sync/1.5
1538159107619	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1538159107620	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1538159107620	Services.Common.RESTRequest	TRACE	HTTP Header x-client-state: cdc794b9bd26b64f527f2387158874a2
1538159107625	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://SERVER/token/1.0/sync/1.5
1538159107625	Services.Common.RESTRequest	TRACE	Channel for GET https://SERVER/token/1.0/sync/1.5 returned status code 0
1538159107625	Services.Common.RESTRequest	DEBUG	GET https://SERVER/token/1.0/sync/1.5 200
1538159107625	Services.Common.RESTRequest	TRACE	GET body: {"uid": 1, "hashalg": "sha256", "api_endpoint": "https://SERVER/storage/1.5/1", "duration": 300, "key": "7QOZw0QYJjUxNkaJH02nPatLij0kR07rkk4E8bHHBIs=", "hashed_fxa_uid": "ID", "id": "eyJub2RlIjogImh0dHBzOi8vZnMuYXJlYTUyLmRuc2hvbWUuZGUiLCAidWlkIjogMSwgImV4cGlyZXMiOiAxNTM4MTU5NDA5LCAiZnhhX3VpZCI6ICIwM2VmZDIwODhlNTY4YzI1ZGE0ZDFjNGY0Yjg4NzFjOSIsICJzYWx0IjogIjJhZDY4ZiIsICJkZXZpY2VfaWQiOiAiNDY4YWI3ZGRjMmNhZjZhYjNkOWMzMjRjNGU5N2NiMjkifVneEeh2uDn9CuvL894lfLSjrlz0klmcsWjaAvzy4DeQ"}
1538159107625	Services.Common.TokenServerClient	DEBUG	Got token response: 200
1538159107625	Services.Common.RESTResponse	TRACE	Processing response headers.
1538159107625	Services.Common.TokenServerClient	DEBUG	Successful token response
1538159107625	Sync.Status	DEBUG	Status.login: success.login => success.login
1538159107626	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1538159107626	Sync.BrowserIDManager	DEBUG	_findCluster returning https://SERVER/storage/1.5/1/
1538159107626	Sync.BrowserIDManager	DEBUG	Cluster value = https://SERVER/storage/1.5/1/
1538159107626	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1538159107626	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1538159107626	Sync.ErrorHandler	ERROR	Sync encountered a login error
1538159107626	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1538159107626	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1538159107627	Sync.Service	DEBUG	Exception calling WrappedLock: Error: Login failed: error.login.reason.network (resource://services-sync/service.js:868:15) JS Stack trace: onNotify@service.js:868:15
1538159107628	Sync.Service	DEBUG	Not syncing: login returned false.
`

i also tried to add a new user - same error. can anyone help me with this?

ths in advance
snIP3r

**Comment by rfk** [comment]
Did anything change about your setup after the recovery, e.g. the URL or path at which your server is being hosted?

**Comment by snIP3r23** [comment]
hi had this issuse: https://github.com/mozilla-services/syncserver/issues/97#issuecomment-402550171 but i found out compiling mod_wsgi with only python 2.7 support solves my previous error. so this seems to be the only "change". no other changes were made...

**Comment by rfk** [comment]
Looks like you're hitting the token-verification error here:

  https://github.com/mozilla-services/server-syncstorage/blob/master/syncstorage/views/authentication.py#L86

Which might indicate a problem with the shared secret between tokenserver and storage node.  Have you configured an explicit secret in your config file?  (The default contents of the file at this point at `#secret = INSERT_SECRET_KEY_HERE`).

**Comment by snIP3r23** [comment]
> Which might indicate a problem with the shared secret between tokenserver and storage node. Have you configured an explicit secret in your config file? (The default contents of the file at this point at `#secret = INSERT_SECRET_KEY_HERE`).
Adding an own secret fixed it! thx for the hint!!!

**Comment by murchu27** [comment]
This fix worked for me too, thanks for raising the issue! Would it be worth adding a point to the section of the docs that describes [running behind a web server](https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html#running-behind-a-web-server) that the secret key should be explicitly configured to get this working?
