### ISSUE TITLE
RuntimeError: cryptography requires setuptools 18.5 or newer

### ISSUE THREAD

**Issue by oschade** [mozilla-services/syncserver#143]
Hello,

I have a problem installing the syncserver on a raspberry pi.
According to the error, I have to upgrade setuptools, but "setuptools" is uptodate (Version 40.4.3).

```
Collecting cryptography (from PyFxA->tokenserver==1.3.0->-r requirements.txt (li                                                                             ne 12))
  Using cached https://files.pythonhosted.org/packages/22/21/233e38f74188db94e84                                                                             51ef6385754a98f3cad9b59bedf3a8e8b14988be4/cryptography-2.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-KQgXm9/cryptography/setup.py", line 28, in <module>
        "cryptography requires setuptools 18.5 or newer, please upgrade to a "
    RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade                                                                              to a newer version of setuptools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-                                                                             KQgXm9/cryptography/
Makefile:22: recipe for target 'local/COMPLETE' failed
make: *** [local/COMPLETE] Error 1

```

I think, you need something like "pip install -U setuptools" in the makefile, but I don't know how this works.

Thank you.

**Comment by rfk** [comment]
Hi @oschade, what version of `virtualenv` do you have installed on your system?  It may be that virtualenv is out-of-date and is installing an older version of setuptools.

**Comment by oschade** [comment]
Thank you! That was the problem!
For others having this trouble: You need to run 

`
sudo pip install virtualenv --upgrade
`

**Comment by hawicz** [comment]
For those of us that can't upgrade virtualenv in that way, because we're in an environment without root, the solution that I found was to:
* Fetch a recent copy of virtualenv from github (e.g. https://github.com/pypa/virtualenv/tarball/debbaa4 for version 16.5.0)
* Extract that and run virtualenv.py from it, then activate the virtual env.
* Use pip download to fetch a current setuptools archive
* Use pip to uninstall setuptools *and* distribute from that environment
* Unzip the setuptools archive and manually run python setup.py install

**Comment by nitinsurana** [comment]
For others if 
`pip install virtualenv --upgrade` 
did not work try 
`pip install -U setuptools`
