### ISSUE TITLE
How to add authentication?

### ISSUE THREAD

**Issue by GildedHonour** [mozilla-services/syncserver#146]
How to add authentication? Does it support it?

**Comment by Mic92** [comment]
I think what @GildedHonour and I want to know if there is a way to make the syncserver not public so that every user could point can store there data on instance in the internet.

**Comment by Mic92** [comment]
Thanks. That make sense.

**Comment by johnwmail** [comment]
Hi, when I set allow_new_users to false, I can not sync again (even old user), any idea?

**Comment by rfk** [comment]
@johnwmail does about:sync-log show any error logs that might provide some clues?

**Comment by johnwmail** [comment]
@rfk  Yes, attacked error log and syncserver.ini
[error-sync-1542685958005.txt](https://github.com/mozilla-services/syncserver/files/2598022/error-sync-1542685958005.txt)
[syncserver.ini.txt](https://github.com/mozilla-services/syncserver/files/2598024/syncserver.ini.txt)

**Comment by rfk** [comment]
OK, looks like the server is throwing an "Internal Server Error", do you get any output in server-side logs?

**Comment by johnwmail** [comment]
No, the nginx error log is nothing/empty,
and the access log is very normal, I attached the access log.
If I comment the " #allow_new_users = false", everything work just fine.
Thanks.
[nginx.log](https://github.com/mozilla-services/syncserver/files/2598113/nginx.log)

**Comment by rfk** [comment]
Are you running under gunicorn with nginx as a proxy? If so, there may be output from the gunicorn process that's separate to the nginx logs (but the location of that output will vary greatly depending on how you're running gunicorn)

**Comment by johnwmail** [comment]
Yes, I am running gunicorn with nginx as a proxy

I add this to /etc/rc.local
/opt/syncserver/local/bin/python2 /opt/syncserver/local/bin/gunicorn --forwarded-allow-ips 10.10.10.150 --paste /opt/syncserver/syncserver.ini


10.10.10.150 is nginx reverse proxy
10.10.10.154 is gunicorn 
and sync.mydomain.net is point to 10.10.10.150

and the related nginx config like this

 location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_redirect off;
                proxy_read_timeout 120;
                proxy_connect_timeout 10;
                proxy_pass http://10.10.10.154:5000/;
        }

**Comment by rfk** [comment]
> I add this to /etc/rc.local

Does this send its output somewhere standard?  I'm not very familiar with running things via rc.local.  You could try gunicorn in the foreground in a terminal rather than via rc.local in order to see any output it produces.

**Comment by johnwmail** [comment]
Ok, I attached the log
the system running gunicorn is debian/lxc and python version is Python 2.7.15+
Thanks.

**Comment by johnwmail** [comment]
sorry, forget to attached, 
[gnuicorn.log](https://github.com/mozilla-services/syncserver/files/2598138/gnuicorn.log)

**Comment by johnwmail** [comment]
I noticed the log, have some error is "encode" and "utf8"....
but do not know what it mean :(

**Comment by rfk** [comment]
Aha, this I recognize:

> AttributeError("'list' object has no attribute 'encode'",)

It's treating the config item "secret" from as a list rather than a string.  I suspect this is caused by the leading space on "allow_new_users = false", which in your config file appears like this:

```
# Set this to "false" to disable new-user signups on the server.
# Only requests by existing accounts will be honoured.
 allow_new_users = false
```

Please try deleting the space character before "allow_new_users" and see if that helps.

**Comment by johnwmail** [comment]
Yes, it work after delete the "space character".
And thank you :) :+1:

**Comment by rfk** [comment]
Glad to hear it :-)
