### ISSUE TITLE
syncserver not build at the moment

### ISSUE THREAD

**Issue by misterhsp** [mozilla-services/syncserver#155]
the syncserver is not building at the moment, I haven't changed anything. I don't know what's stuck there.  Problem with the Alpine-image????
`
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting beautifulsoup4 (from webtest->SyncStorage==1.6.13->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/8b/0e/048a2f88bc4be5e3697df9dc1f7b9d5c9c75be62676feeeb91d2e896c5ea/beautifulsoup4-4.7.1-py2-none-any.whl (94kB)
Collecting waitress>=0.8.5 (from webtest->SyncStorage==1.6.13->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/b4/1e/3b51f5a9454a1f15ae5b82a7044e095c93eeefd2d1e5738e588fc43c9e89/waitress-1.2.1-py2.py3-none-any.whl (140kB)
Collecting linecache2 (from traceback2->unittest2==1.1->-r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/c7/a3/c5da2a44c85bfbb6eebcfc1dde24933f8704441b98fdde6528f4831757a6/linecache2-1.0.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.9.2 (from Mako->alembic->tokenserver==1.3.0->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/ac/7e/1b4c2e05809a4414ebce0892fe1e32c14ace86ca7d50c70f00979ca9b3a3/MarkupSafe-1.1.0.tar.gz
Collecting cffi!=1.11.3,>=1.8 (from cryptography->PyFxA->tokenserver==1.3.0->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz (438kB)
Collecting ipaddress; python_version < "3" (from cryptography->PyFxA->tokenserver==1.3.0->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography->PyFxA->tokenserver==1.3.0->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
Requirement already satisfied, skipping upgrade: enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography->PyFxA->tokenserver==1.3.0->-r requirements.txt (line 11)) (1.1.6)
Collecting soupsieve>=1.2 (from beautifulsoup4->webtest->SyncStorage==1.6.13->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/bf/b3/2473abf05c4950c6a829ed5dcbc40d8b56d4351d15d6939c8ffb7c6b1a14/soupsieve-1.7.3-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->PyFxA->tokenserver==1.3.0->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
Collecting backports.functools-lru-cache; python_version < "3" (from soupsieve>=1.2->beautifulsoup4->webtest->SyncStorage==1.6.13->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/usr/lib/python2.7/site-packages/pip/_internal/wheel.py", line 886, in build
    assert have_directory_for_build
AssertionError
`

Greetings
      Holger...

**Comment by johnwmail** [comment]
I remember, it because alpine openssl/lib apk, build without some function is needed by syncservser.

**Comment by misterhsp** [comment]
I can't get the syncserver built like this anymore. Always the same error.

...

**Comment by rfk** [comment]
Thanks for the report!  ooks like this is failing in our CircleCI builds as well. Maybe related to https://github.com/pypa/pip/pull/6171

**Comment by rfk** [comment]
@misterhsp I've pushed a fix based on comments at [1], could you please try latest master and see if that worked for you?

[1] https://github.com/pypa/pip/issues/6158#issuecomment-457320306

**Comment by misterhsp** [comment]
Thanks Ryan for the quick fix. With the fix it works again.


Greetings
     Holger....



Am 29.01.19 um 01:02 schrieb Ryan Kelly:
