### ISSUE TITLE
Docker secret environment variable

### ISSUE THREAD

**Issue by ThaChillera** [mozilla-services/syncserver#161]
In the docker instructions in readme.md there is an example, that includes a secret. Users could blindly copy this example and use a non-secret secret.

Might it be an idea to change this value to \<SECRET\>, and maybe link to [here](https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html#further-configuration) so users can learn how to generate their own secret?

**Comment by rfk** [comment]
Thanks for the suggestion! I've updated the docs in https://github.com/mozilla-services/syncserver/pull/162
