### ISSUE TITLE
public_url doesn't match application_url

### ISSUE THREAD

**Issue by Ahava** [mozilla-services/syncserver#163]
Since I upgraded the syncserver software a few days ago my browser won't sync anymore giving me the following error:

```
ERROR:syncserver:The public_url setting doesn't match the application url.  
This will almost certainly cause authentication failures!  
    public_url setting is: https://sync.myserver.com  
    application url is:    https://sync.myserver.com/
```

The thing is though that I've set public_url in the config to "https://sync.myserver.com/" instead of what it says. The software is running behind an nginx reverse proxy.

What I've tried so far is:

- Reset config to default and just fill in `public_url`, `sqluri` and `secret`.
- Run the process manually instead of running it through systemd.
- Restart the webserver.

**Comment by rfk** [comment]
Could you please try changing `force_wsgi_environ` to `true` in your config file and see if that fixes the error? We can debug further to find out the underlying cause, but this is a good way to confirm whether it is indeed this mismatch that's causing the sync failures.

**Comment by Ahava** [comment]
Okay with `force_wsgi_environ` set to `true` I get the following error in `about:sync-log`: https://pastebin.com/xZCnPmTM

And this error on the server side:
```
[pid: 8202|app: 0|req: 1/1] XXX.XXX.XXX.XXX () {50 vars in 2956 bytes} [Sun Mar 17 22:28:02 2019] GET /token/1.0/sync/1.5 => generated 1 bytes in 1 msecs (HTTP/1.1 404) 4 headers in 151 bytes (1 switches on core 0)
```

I've got `allow_new_users` set to `true` aswell.

I'm using Firefox Developer Edition `67.0b2`

**Comment by rfk** [comment]
> Error processing token server response: TypeError: right-hand side of 'in' should be an object, got number(resource://services-common/tokenserverclient.js:302:11)

Yikes; this I have not seen before.  But it looks like maybe it's just trying to parse a 404 response body:

> GET https://sync.myserver.com/token/1.0/sync/1.5 404

If you visit https://sync.myserver.com/token/1.0/sync/1.5 manually in your browser, does it give you a 404?  What if you visit just https://sync.myserver.com/token/ ?

**Comment by Ahava** [comment]
If I visit `https://sync.myserver.com/token/1.0/sync/1.5` I get `0` as response with an `application/json; charset=UTF-8` response header. Same with `https://sync.myserver.com/token/`

Accessing just `https://sync.myserver.com/` I get `it works!`

My nginx config is: https://pastebin.com/4T66pXBE
And I start my systemd unit file is: https://pastebin.com/ncYcejkN

**Comment by rfk** [comment]
> Same with https://sync.myserver.com/token/

That's defnitely not right; visitin `/token` is supposed to give you a list of the available services and auth mechanisms on this server.  It sounds like the app is, for some reason, not correctly routing requests to the right handlers.

Unfortunately I don't know enough about uwsgi to suggest what might be doing wrong here.  If you start the some `syncserver.ini` using `gunicorn` rather than `uwsgi`, do you see the same behaviour?  (The Makefile has an example of how to run with `gunicorn` if you need one).

**Comment by Ahava** [comment]
>  If you start the some syncserver.ini using gunicorn rather than uwsgi, do you see the same behaviour?

Just tried it out, still getting the `0` response with an `application/json` content type.

Here are the whole headers for reference:
```
Connection: close
Content-Length: 1
Content-Security-Policy-Report-Only: worker-src 'none'; report-uri about:blank
Content-Type: application/json; charset=UTF-8
Date: Sat, 23 Mar 2019 02:50:18 GMT
Server: gunicorn/19.6.0
X-Timestamp: 1553309418
X-Weave-Timestamp: 1553309418.71

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en,de;q=0.7,en-US;q=0.3
Connection: keep-alive
DNT: 1
Host: myserver.com:5000
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

```

**Comment by triplepoint** [comment]
Make sure you're observing the trailing slash.  I noticed that https://sync.myserver.com/token returns "0" and https://sync.myserver.com/token/ returns the expected JSON body.

**Comment by Ahava** [comment]
After triplepoint pointing out that observing the trailing slash is important when requesting `token` I tried it again and it worked. So I went back, put the gunicorn hosted version into the Firefox config and it syncs again! Seems to be an issue then with uwsgi, thanks a ton to everyone who helped out!
