### ISSUE TITLE
Docker container does not write logs

### ISSUE THREAD

**Issue by danielandross** [mozilla-services/syncserver#164]
I am experiencing a "500 Server Error: Internal Server Error" when executing the testsuite in a docker container. /var/log/ directory is empty. Is this normal behavior? Where are logs written to? Regards

**Comment by danielandross** [comment]
Would somebody please tell me how to debug my syncserver docker container? Regards

**Comment by rfk** [comment]
Sorry, the docker stuff is mostly maintained by third-party contributors so I can't offer many tips on debugging it.  I'd expect the logs to be written to stdout by default, but can't say for sure.

Note that in its default configuration the server doesn't log much; you should be able to add logging configuration to `syncserver.ini` following the python logging module's file-config syntax:

  https://docs.python.org/2/library/logging.config.html#configuration-file-format

For example, here's a snippet of the logging config we use in production:

```
[loggers]
keys = root, gunicorn

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_gunicorn]
level = WARN
handlers = console
qualname = gunicorn

[handler_console]
class = StreamHandler
args = (sys.stdout,)

**Comment by sbraz** [comment]
How about adding a very simple `SYNCSERVER_DEBUG` option that changes https://github.com/mozilla-services/syncserver/blob/e1aab54cbcb6e570979835789f7b4624eebdc875/syncserver/__init__.py#L146 to `logging.DEBUG`?

Surely that would be enough to help troubleshoot.
