### ISSUE TITLE
API specification

### ISSUE THREAD

**Issue by akramer-zibra** [mozilla-services/syncserver#175]
Is there any API specifiation for syncserver? or some API test code?

**Comment by thomcc** [comment]
This might be what you're looking for https://mozilla-services.readthedocs.io/en/latest/sync/index.html

**Comment by akramer-zibra** [comment]
Great. Thanks!

Am 18. Juni 2019 20:03:39 MESZ schrieb Thom Chiovoloni <notifications@github.com>:
>This might be what you're looking for
>https://mozilla-services.readthedocs.io/en/latest/sync/index.html
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla-services/syncserver/issues/175#issuecomment-503247021

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
