### ISSUE TITLE
BUG/Question: Removing Mozilla-hosted data

### ISSUE THREAD

**Issue by githtz** [mozilla-services/syncserver#176]
What I did:
```log
python ./bin/delete_user_data.py myuser@myserver.net
```
The script asked for my password
```log
Password for myuser@myserver.net:
```

What I got:
```log
Traceback (most recent call last):
  File "./bin/delete_user_data.py", line 91, in <module>
    main(sys.argv[1:])
  File "./bin/delete_user_data.py", line 50, in main
    s = c.login(args.email, password, keys=True)
  File "/home/oh2b1448ec6a/.local/lib/python2.7/site-packages/fxa/core.py", line 90, in login
    resp = self.apiclient.post(url, body)
  File "/home/oh2b1448ec6a/.local/lib/python2.7/site-packages/fxa/_utils.py", line 335, in post
    return self.request("POST", url, json, **kwds)
  File "/home/oh2b1448ec6a/.local/lib/python2.7/site-packages/fxa/_utils.py", line 321, in request
    raise fxa.errors.ClientError(body)
fxa.errors.ClientError: Incorrect email case
```
Looks like something is supposed to be wrong with the email case - but why?

Thanks in advance!

// EDIT 

Oh dumb me, is this because of 2FA?

**Comment by fireglow** [comment]
`./bin/delete_user_data.py` only works for data stored on your own server, not the data on the Mozilla servers.

**Comment by githtz** [comment]
Okay, now I am confused - according to the documentation it's meant for Mozilla hosted data.

[Removing Mozilla-hosted data](https://github.com/mozilla-services/syncserver#removing-mozilla-hosted-data)
> If you have previously uploaded Firefox Sync data to the Mozilla-hosted storage service and would like to remove it, you can use the following script to do so:

**Comment by fireglow** [comment]
Oh shucks, I am confused and you are correct!
Things you can try:
Go to https://accounts.firefox.com/settings , sign in, and copy the email address that is displayed on the top, under your name, to use with the script;
Disable 2FA;
There is a third option, which should only be used in extreme cases, which is to delete and re-create the Firefox account.

**Comment by githtz** [comment]
Okay, thank you. I'll try the suggested options in that order and report back afterwards!
