### ISSUE TITLE
StaticNodeAssignment does not match TokenServer 

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncserver#191]
While running a local tokenserver I hit the following:
```
...
  File "/home2/jrconlin/src/mozilla/syncserver/venv/local/lib/python2.7/site-packages/tokenserver/views.py", line 378, in return_token
    keys_changed_at=keys_changed_at)
TypeError: allocate_user() got an unexpected keyword argument 'keys_changed_at'
```

It appears that the `syncserver` no longer matches arguments with Tokenserver 1.5.4

**Comment by rfk** [comment]
Ugh, right. I had forgotten that this uses a special simplified backend for self-hosting purposes. We'll need to either port the keys-changed-at changes over to this repo, or rejigger things so that it can use the same backend code as we use for tokenserver in production.

**Comment by jrconlin** [comment]
Yeah, this is more a placeholder bug. Once I finish fiddling with the stand alone for the migration tool, I'll try to put together a PR that matches things up. For now, I've added the `keys-changed-at` and `node` stuff over and that's working for me.
