### ISSUE TITLE
Unable to build - "Package 'soupsieve' requires a different Python"

### ISSUE THREAD

**Issue by csolisr** [mozilla-services/syncserver#205]
As of today, the sync server seems to be impossible to build, as one of the current dependencies, Soupsieve, no longer supports Python 2. As per the build log:

```
Collecting soupsieve>=1.2
  Using cached https://www.piwheels.org/simple/soupsieve/soupsieve-2.0-py2.py3-none-any.whl (35 kB)
ERROR: Package 'soupsieve' requires a different Python: 2.7.16 not in '>=3.5'
make: *** [Makefile:29: local/COMPLETE] Error 1
```

Is there a way to bypass this in order to use a Python 2 - compatible version of Soupsieve, or will I have to wait until the Rust rewrite is ready for production?

**Comment by jrconlin** [comment]
Hmm. it may be possible to vendor lock to a prior version of soupsieve, but I'm not sure what the dependency chain might be. It looks like 1.9.5 is the last 2.7 compatible version.

A possible fix might be to add 
`soupsieve==1.9.5` to the `requirements.txt` file.

**Comment by jlaptavi** [comment]
Ran into this issue today and setting `soupsieve==1.9.5` in the `requirements.txt` file did solve the issue for me.
