### ISSUE TITLE
Documentation site broken (infinite redirects)

### ISSUE THREAD

**Issue by anthony-geoghegan** [mozilla-services/syncserver#210]
Hi there,

As always, I like to read the official documentation before using/installing new software. 

However, the [documentation site](https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html) listed in the README is broken.  Attempts to request any URL from <https://mozilla-services.readthedocs.io> results in an infinite series of *301 Moved Permanently* redirects.

Is this the most appropriate place to report this issue - or should I use the Mozilla Bugzilla?

**Comment by rfk** [comment]
Thanks for reporting this, I've tweaked some settings on https://mozilla-services.readthedocs.io that should help, and I've filed a bug in bugzilla to investigate further: https://bugzilla.mozilla.org/show_bug.cgi?id=1634992

**Comment by anthony-geoghegan** [comment]
@rfk Thanks for that. I have a Bugzilla account but haven't used it for many years.

In any case, even though there was no response to your Bugzilla issue, it looks like the admins rectified that redirection issue so I can probably close this issue now.
