### ISSUE TITLE
Tab syncing no longer works after Firefox update

### ISSUE THREAD

**Issue by theWatchmen** [mozilla-services/syncserver#220]
I have been a happy user of syncserver for a long time and I am really grateful to the developers of this service. After a recent update to Firefox 78, it seems I can no longer sync tabs across devices. I have upgraded to the latest version on the master branch, but the synced tabs list remains empty. The version of Firefox is 78 and I am running it on Linux (Debian 10) and macOS 10.14. The server is Debian 9 and I am using nginx.

I run into issue #214 a while back, but after following the suggestions in the issue I was able to get sync working. Now it seems I am having troubles again. If I try to send a tab to another device it seems to be working fine. I checked the database and I can see that the bso table is populated.

I checked the logs both for nginx and syslog and I couldn't find any error messages there. The post request logged returns a 200, so it seems everything is working correctly.

I realise this is a bit vague, please let me know if you need further details.

[EDIT]: the service is using an https connection.

**Comment by rfk** [comment]
> The version of Firefox is 78 and I am running it on Linux (Debian 10) and macOS 10.14. 

The most likely source of debugging information here will be the client-side sync logs. If you go into `about:sync-log` on each of your two devices, do they have any error logs?

If there's a recent error log, take a look and see if it contains any errors about syncing tabs, which might give a clue.

If there are no error logs, you can flipping the `services.sync.log.appender.file.logOnSuccess` config option on via `about:config`, and then sync again. This should generate some success logs. If you look in the success logs it should give some info about what the client sees when it tries to sync each collection, which might offer some clues.

You could also try installing the [`about:sync` addon](https://addons.mozilla.org/en-US/firefox/addon/about-sync/). This will provide you with the ability to visit `about:sync` in your browser and get an overview of the state of your synced data. You could poke around in the "tabs" section of that report and see if anything looks odd.

Sorry for the vague suggestions but I don't know exactly what might be causing this, so the best I can offer for the moment is some advice on hunting for further clues.

**Comment by theWatchmen** [comment]
Thanks for your reply Ryan. I checked the logs and everything looked fine. I tried logging out and logging in again in Firefox and that did the trick... From the logs it seems that the client thought all tabs were already up to date. Either way, it seems to be working fine now :) Good to know about the sync-log.
