### ISSUE TITLE
Bookmars are not synced anymore to\from mobile platforms.

### ISSUE THREAD

**Issue by vcarciu** [mozilla-services/syncserver#221]
Environments:
Firefox for iOS(27.0(18428)), Firefox Preview(Nightly 200720, build #22020612)
FF Release(78) on macOS and Windows 10x64
FXA stage version : 1.180.0

Steps to reproduce:
1. Set-up the FXA server to Stage on every platform(https://accounts.stage.mozaws.net)
2. Login with same valid FXA on multiple platforms(Windows, macOS, Android and iOS)
3. Add some bookmarks on any every platform and force a Sync everywhere

Expected results:
Bookmarks are synced across all platforms

Actual results:
On mobile platforms , bookmarks are not synced at all(from desktop to mobile, from mobile to desktop, from mobile to mobile). 

NOTES:
Not reproducible with production FXA server
Between desktop platforms , bookmarks syncing is working as expected

**Comment by vcarciu** [comment]
Please note that we observed that between mobile devices not only bookmarks syncing is broken. We were not able to sync history and passwords too.

**Comment by vladikoff** [comment]
from Slack for users on stage:

| 537f342abb2d4869a2f9ae4f1545ee7a ||
| ccc8ec0e8d514e5b9e969ad5500f15f9 ||

> do not see any requests that do not get a 200 response code

**Comment by vladikoff** [comment]
Also filed https://github.com/mozilla/application-services/issues/3379

@vcarciu is this the configuration that you are using in your Fenix build:

<img src=https://user-images.githubusercontent.com/128755/87977594-01608380-ca9d-11ea-96d5-52e35744498b.png width=500 />

?

**Comment by vcarciu** [comment]
@vladikoff : 

Yes, I can confirm that sync is not working on Fenix with the configuration from above. Also, on FF for iOS , I checked the "Use stage servers" checkbox from "Advanced sync settings".

Thank you

**Comment by vcarciu** [comment]
I attached some logs gathered with adb logcat from Android: 
[Fenixlogs.txt](https://github.com/mozilla-services/syncserver/files/4954579/Fenixlogs.txt)

**Comment by mhammond** [comment]
> I attached some logs gathered with adb logcat from Android:

Thanks for the logs, but unfortunately there's only 30 seconds of logs there and there's no evidence of a sync in that period.

**Comment by vladikoff** [comment]
@mhammond we have some logs in https://github.com/mozilla/application-services/issues/3379

**Comment by vcarciu** [comment]
I am not sure where this was fixed, but the sync on mobile platforms is now working as expected. Please let me know if we can close this issue.

**Comment by jrconlin** [comment]
We've resumed migrations. It could be that your profile has been moved to
the new durable sync service.

**Comment by vcarciu** [comment]
@jrconlin 

Issue is reproducible again for mobile devices. Do you know if migrations are the cause this time too?

**Comment by isabelrios** [comment]
Experiencing this issue also when running the automated sync integration tests. Got some firefox logs in case that's helpful
[FirefoxLogsSyncHistoryFenix.pdf](https://github.com/mozilla-services/syncserver/files/5017681/FirefoxLogsSyncHistoryFenix.pdf)
On Fenix also happening for History.
It shows at the beginning that the Sync never happened and forcing sync it shows: Last synced: Jan 1, 1970

**Comment by mhammond** [comment]
See also https://github.com/mozilla/application-services/issues/3379

**Comment by mhammond** [comment]
> Experiencing this issue also when running the automated sync integration tests. Got some firefox logs in case that's helpful
> [FirefoxLogsSyncHistoryFenix.pdf](https://github.com/mozilla-services/syncserver/files/5017681/FirefoxLogsSyncHistoryFenix.pdf)

These are just desktop logs (and almost impossible to read as a PDF - it's much better if they are left as plain text) - so I can't be sure it's the same issue being described here.

**Comment by rfk** [comment]
I believe this to be an issue with the rust-based sync server, let's close it here in favour of https://github.com/mozilla-services/syncstorage-rs/issues/759

**Comment by isabelrios** [comment]
> These are just desktop logs (and almost impossible to read as a PDF - it's much better if they are left as plain text) - so I can't be sure it's the same issue being described here.

Sorry about that,  I saw an error in the Firefox logs and though it was related but it is not. The error on the mobile side is not shown there. That said, the error is the same on Fenix and Firefox iOS.
For Fenix can't sync Bookmarks/History
For Firefox-iOS History works but Bookmark does not
Both using stage
