### ISSUE TITLE
Firefox Android 79.0.5 has removed the `about:config` page

### ISSUE THREAD

**Issue by murchu27** [mozilla-services/syncserver#223]
The latest update for Firefox Android has removed the `about:config` page, making it impossible to set the value of `identity.sync.tokenserver.uri` so that one's own sync server can be used.

https://ibb.co/gW6T8zk
https://ibb.co/vPbYrWg

I was already signed in with sync working before the update, but it's signed me out as part of the update, and now I can't sync it with my server.

**Comment by mhammond** [comment]
This isn't a server bug - bugzilla or https://github.com/mozilla-mobile/fenix/ would be more appropriate.

However, you could try opening the about page and tapping the Firefox logo a number of times - you should see a toast telling you debug options are available. "Custom Sync Server" should then appear in the top-level account section. I've never actually used it so I'm not 100% sure how well it works.
