### ISSUE TITLE
Seeing 401 Errors when Firefox upgraded to version 80

### ISSUE THREAD

**Issue by amartin-git** [mozilla-services/syncserver#224]
Setup was working fine under Firefox 79 (using both Docker and standalone versions of syncserver). After updating Firefox to version 80, users started seeing the 'Reconnect to Firefox Account' notification. The sync log shows correct authorization to the Mozilla accounts server, but syncserver is returning a 401 error. Switching to Mozilla's tokenserver.uri works.

Users still on Firefox 79 do not get these errors.

Anyone else experiencing this?

**Comment by radwiimp** [comment]
Seeing the same issue here after updating to version 80, using docker syncserver.

**Comment by vladikoff** [comment]
@radwiimp @amartin-git try flipping these to false and trying again:
![image](https://user-images.githubusercontent.com/128755/91498485-d6cccc00-e88d-11ea-8d1f-9a465725428d.png)

**Comment by radwiimp** [comment]
I received a new login e-mail from Firefox after trying that, but still having the same issues

**Comment by radwiimp** [comment]
That seemed to do the trick for me, working now.

**Comment by amartin-git** [comment]
@vladikoff Yes, that fixed it. Thanks so much!

**Comment by chr15m** [comment]
This worked for me too.
