### ISSUE TITLE
syncserver builderror since the last commits

### ISSUE THREAD

**Issue by misterhsp** [mozilla-services/syncserver#238]
I'm getting these error messages since the last commits when building the syncserver. The build is successful and it seems that everything works. Can I ignore this? Or is there a solution?

Thanks...

100% |████████████████████████████████| 81kB 8.6MB/s 

requests 2.20.0 has requirement idna<2.8,>=2.5, but you'll have idna 2.8 which is incompatible.
requests 2.20.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
gevent 1.4.0 has requirement greenlet>=0.4.14; platform_python_implementation == "CPython", but you'll have greenlet 0.4.13 which is incompatible.
tokenserver 1.5.11 has requirement configparser==3.7.4, but you'll have configparser 3.5.0 which is incompatible.
tokenserver 1.5.11 has requirement cornice==3.5.1, but you'll have cornice 0.16.2 which is incompatible.
tokenserver 1.5.11 has requirement gunicorn==19.10.0, but you'll have gunicorn 19.6.0 which is incompatible.
tokenserver 1.5.11 has requirement mozsvc==0.10, but you'll have mozsvc 0.9 which is incompatible.
tokenserver 1.5.11 has requirement pyramid==1.10.4, but you'll have pyramid 1.5.3 which is incompatible.
tokenserver 1.5.11 has requirement requests==2.22.0, but you'll have requests 2.20.0 which is incompatible.
tokenserver 1.5.11 has requirement WebOb==1.8.5, but you'll have webob 1.4.1 which is incompatible.
google-api-core 1.22.2 has requirement futures>=3.2.0; python_version < "3.2", but you'll have futures 3.0.0 which is incompatible.
Installing collected packages: WebOb, zope.deprecation, repoze.lru, PasteDeploy, translationstring, zope.interface, venusian, pyramid, simplejson, cornice, guni

**Comment by rfk** [comment]
Thanks for the heads-up. They're safe to ignore AFAICT. I tried working through the list and updating them to fix the warnings, but didn't complete it (basically it's a manual process of syncing up dependency versions between the ones pinned in this repo and hte ones pinned in `tokenserver` and `server-syncstorage`).

**Comment by fzzzy** [comment]
Since it seems these are safe to ignore, I will close this. Reopen if there's anything else needed here.
