### ISSUE TITLE
HTTP 401 with multiple accounts and release 1.9.0

### ISSUE THREAD

**Issue by mt7479** [mozilla-services/syncserver#241]
Since upgrading to 1.9.0 I'm unable to sync with my second account.

Webserver log:
```
xxx - - [14/Sep/2020:20:50:21 +0200] "GET /storage/1.5/1/info/collections HTTP/2.0" 401 79 "-" "Firefox/80.0.1 (Linux x86_64) FxSync/1.82.0.20200831163820.desktop"
```

Config:

```
[server:main]
use = egg:gunicorn
host = 0.0.0.0
port = 5000
workers = 1
timeout = 30

[app:main]
use = egg:syncserver
[syncserver]
public_url = https://sync.example.com/
identity_provider = https://accounts.firefox.com/
secret = supersecret
allow_new_users = true
force_wsgi_environ = false
sqluri = sqlite:////path/syncserver.db
```

git checkout 1.8.0 resolved the issue for me. Before that i've tried:

* force_wsgi_environ = true
* disconnecting and reconnecting the machines using the second account

with no success.

**Comment by rfk** [comment]
> upgrading to 1.9.0 

Whoops, I need to make a new tag with recent fixes in it. Thanks.

**Comment by rfk** [comment]
I've tagged a `1.9.1`, could you please try with that?

**Comment by mt7479** [comment]
> 
> 
> I've tagged a `1.9.1`, could you please try with that?

Working again, thank for the quick fix!
