### ISSUE TITLE
Update syncserver package to use the new syncstorage-rs module.

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncserver#246]
As Python 2.7 is now end of life, Mozilla has been working toward reimplementing the syncstorage backend in rust. This is now complete. https://github.com/mozilla-services/syncstorage-rs

Now that syncstorage-rs is ready for use, we should update this repo to use it.

**Comment by fzzzy** [comment]
Will give this an estimate once I have some time to dig into how much there is to do.

**Comment by MichaIng** [comment]
This is radical, broke all installers an integrations. I thought the Rust-based server will be a new repository (it is, but I mean the combined AIO repo with tokenserver-rs included). This seems like a patchwork to me now and I guess the basis will change quickly until full migration to the Rust-based system has finished?
