### ISSUE TITLE
Sync is broken with Firefox Android since v82.x. What could be the reason?

### ISSUE THREAD

**Issue by kommserv** [mozilla-services/syncserver#261]
On `Debian 10` (GNU/Linux 4.19.0-6-amd64 x86_64), after starting `syncserver` over from scratch with the latest git master and a new empty SQL database to go with it. All dependencies installed, and the server has the latest apt updates.
```
Apache		 2.4.38-3+deb10u4
PHP		 7.3.24-3+0~20201103.72+debian10~1.gbp945915
Firefox sync	 1.9.1-10-g58b8036
Python		 3.7.3; 2.7.16
pip		 18.1; 18.1
Git		 2.20.1
MariaDB		 Ver 15.1 Distrib 10.3.25-MariaDB
```

Towards the end of the `make build` output, I get this block in red text saying "error":
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

requests 2.20.0 requires idna<2.8,>=2.5, but you'll have idna 2.8 which is incompatible.
requests 2.20.0 requires urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
gevent 1.4.0 requires greenlet>=0.4.14; platform_python_implementation == "CPython", but you'll have greenlet 0.4.13 which is incompatible.
tokenserver 1.5.11 requires configparser==3.7.4, but you'll have configparser 3.5.0 which is incompatible.
tokenserver 1.5.11 requires cornice==3.5.1, but you'll have cornice 0.16.2 which is incompatible.
tokenserver 1.5.11 requires gunicorn==19.10.0, but you'll have gunicorn 19.6.0 which is incompatible.
tokenserver 1.5.11 requires mozsvc==0.10, but you'll have mozsvc 0.9 which is incompatible.
tokenserver 1.5.11 requires pyramid==1.10.4, but you'll have pyramid 1.5.3 which is incompatible.
tokenserver 1.5.11 requires requests==2.22.0, but you'll have requests 2.20.0 which is incompatible.
tokenserver 1.5.11 requires WebOb==1.8.5, but you'll have webob 1.4.1 which is incompatible.
google-api-core 1.23.0 requires futures>=3.2.0; python_version < "3.2", but you'll have futures 3.0.0 which is incompatible.
```

But apart from that, `make build` does not appear to complain and finishes normally. Running `make test` completes without errors, but with a warning (that also persists in the Apache error log later):
```
/home/kommserv/public/syncserver/local/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

I then put my settings into `syncserver.ini` (shown below) in place, and with a clean SQL database, restart apache.

**Sync now works between Firefox on two desktops (78.5esr)**.
But however I try, with Firefox 83 on Android, or Fennec 82 on Android, *syncing from mobile simply **does not** work*!

I've tried setting the "Custom Sync server" address as `https://ffsync.mydomain.com` or `https://ffsync.mydomain.com/token/1.0/sync/1.5`, (logging out and restarting Firefox in between changes) but in both cases, **the Apache access log shows the same 404 error** when the mobile device attempts to sync:
```
37.2.12.058 - - [23/Nov/2020:20:40:17 +0100] "GET /1.0/sync/1.5 HTTP/1.1" 404 343 "-" "Mozilla/5.0 (Android 6.0.1; Mobile; rv:82.0) Gecko/82.0 Firefox/82.0"
```

+ Do you think the error message during `make build` has any bearing on these sync problems?
+ What about the `RequestsDependencyWarning`? #233 
+ If none of these issues have any bearing on the situation, then what could be causing the total sync failure from Firefox/Fennec on Android? Can anyone reproduce the broken sync?

I've had Firefox Sync running for years, without major issues. But ever since the Firefox on Android was overhauled a couple of months ago, sync from my mobile devices has not worked. If Mozilla really intends to break self-hosted sync for mobile devices, or from all devices, I would appreciate an honest heads-up. It feels to me like Firefox on mobile is evolving so fast, that other Mozilla projects are playing catch-up, leaving those of us self-hosting Sync with broken systems. Even quite recent suggested fixes (#218, #224, #225, [#14595](https://github.com/mozilla-mobile/fenix/issues/14595)) are not relevant anymore (there's no `about:config` on Firefox 83.x, and a subset of one in Fennec 82.x, and in both cases "debug mode" does not appear to reintroduce a complete `about:config` or any `about:sync-log`). 

Relevant lines from my `syncserver.ini`:
```
[server:main]
use = egg:gunicorn
host = 0.0.0.0
port = 5000
workers = 2
timeout = 60

[app:main]
use = egg:syncserver

[syncserver]
public_url = https://ffsync.mydomain.com
identity_provider = https://accounts.firefox.com/
secret = <secret>
allow_new_users = true
force_wsgi_environ = true
```

**Comment by fzzzy** [comment]
Thanks for the report. I'm not aware of any intentional changes that would have broken this.

It looks to me like something might be wrong with the urls... The fact that your tokenserver is on https://ffsync.mydomain.com/token/1.0/sync/1.5 but the 404 is for the url /1.0/sync/1.5 seems wrong.

We definitely don't intentionally intend to break self hosting, but we've been doing a lot of work on syncstorage-rs over the last year and will continue to do so, so there may be rough bumps. We don't have a lot of test coverage of self hosting setups, so it's hard to tell when we break things.

**Comment by rfk** [comment]
This sounds like a known bug in URL handling in Fenix, which has been fixed in development but it awaiting various releases before it goes out to users. There is a workaround documented [here](https://github.com/mozilla-mobile/fenix/issues/15590#issuecomment-722001692).

**Comment by kommserv** [comment]
@rfk Thank you, setting the URL to `https://ffsync.mydomain.com/token/` in Firefox Android worked! (N.B. This change fixed sync for me not only in Fennec but in Firefox Android too).

@fzzzy Thanks for taking the time to respond :-) I really appreciate your answer, and sorry for my little rant (it was at the tail end of a few hours of trying to coax Sync into working). Keep up the good work!
