### ISSUE TITLE
What happens now?

### ISSUE THREAD

**Issue by misterhsp** [mozilla-services/syncserver#264]
What happens now with the syncserver? Does it now come to Python3 or does it stay with python2?

Thanks...

**Comment by ronny332** [comment]
👍

**Comment by Stars-** [comment]
I didn't realize that this team was so small. Thank you for allowing me to rest easy knowing that my data is in my own hands!

**Comment by assarbad** [comment]
@jrconlin Will this project announce (e.g. via its README) that it has been replaced, once that is the case? Thanks.

**Comment by gtozzi** [comment]
> The official plan is to replace the python version with [a newer rust based version](https://github.com/mozilla-services/syncstorage-rs). While we've done this internally, we've not yet packaged things up quite as elegantly here.
> 
> To do that, we're working on integrating [the token server into syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs/issues?q=is%3Aissue+is%3Aopen+tokenserver), as well as some kinks in continuing to support local SQL databases. Then we'll have to package things up into an appropriate release (more than likely, this will be something like Docker) and update documents where needed.
> 
> Let me also note that we're a very small team (3 people) working on several different critical services and have a significant backlog on all of them. Our first priority is to make sure that our systems are running, efficient and maintainable. This means that we can't offer any schedule for when any of this will be available since we can't predict what sort of fires or emergencies will happen that will demand our attention.
> 
> We do, quite happily, accept pull requests and community contributions, and all of our code is open source.

Thank you for finding time to write this comment. I am having lots of issues building this server due to obsolete pytohn2 requirements: looks like it is no longer buildable in modern systems.

Luckily your comment pointed me to the new syncstorage-rs. I have easily built and installed it under Ubuntu 20.04 using the instructions provided in the README.md there. Looks like it is complete and elegant enough; unfortunately, by reading the docs, it looks like it still relies on this python2 syncserver to work? Isn't there a way to run it standalone?

**Comment by kkarhan** [comment]
So how's the status?
https://github.com/mozilla-services/syncserver/issues/264#issuecomment-754784657

**Comment by kkarhan** [comment]
Cuz as of now it's not working...
https://github.com/mozilla-services/syncstorage-rs/issues/1398

**Comment by godfuture** [comment]
Old sync is being dropped and declared deprecated, before the new rust is out in the wild. This basically means that we are left with no solution. The rust project still says their docker images are nothing else but tests and this should explain the silence in their project and documenation.

Wow, well managed I would say...

**Comment by mhammond** [comment]
The new rust code is out in the wild and has been running in production for some time. We do however need external help to make it easy to self-host.
