### ISSUE TITLE
syncserver is deprecated but still used by syncstorage-rs

### ISSUE THREAD

**Issue by canoine** [mozilla-services/syncserver#295]
Hello,

I noticed that , hem, "**Note that this repository is deprecated**". And I understand why: indeed, Python 2 isn't maintained anymore for much months now.

But... syncstorage-rs readme points to... syncserver, and tokenserver-rs seems not ready to use. So, is there a way to self-store my firefox settings, without using syncserver ?

**Comment by mhammond** [comment]
See the discussion in #294 - so not today, but we are working on it!
