### ISSUE TITLE
import password from edge or csv file to Firefox，cannot sync

### ISSUE THREAD

**Issue by ilisten** [mozilla-services/syncserver#296]
i import password from edge to firefox
but after another firefox (with same firefox account) sync success, no password

i tried to import password from csv file to firefox, but still cannot sync password to another firefox

can someone help me?thanks

firefox version: 97.0.2 windows 64bit

**Comment by Geocali** [comment]
I have the same problem, importing in firefox passwords from a csv generated by firefox

firefox 100.0 linux 64 bits

**Comment by mhammond** [comment]
This is being tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1768792
