### ISSUE TITLE
ImportError ExtendedInterpolation

### ISSUE THREAD

**Issue by simonsmiley** [mozilla-services/syncserver#39]
Hi there, 
I just cloned the repo and ran make build which went fine. Trying to start the server I get "ImportError: cannot import name ExtendedInterpolation"
I wonder if I'm doing something wrong...
Using Debian 6 python2.7, python2.7-dev and python2.7-virtualenv are installed as required

**Comment by jonassmedegaard** [comment]
seems this was closed without reverting the pinning

**Comment by rfk** [comment]
updated to latest (fixed) configparser version in https://github.com/mozilla-services/syncserver/commit/7cc82ba7255b66e1b74e72c9ad8b8d88ece71f8a
