### ISSUE TITLE
Useless error if tokenserveruri totally misconfigured

### ISSUE THREAD

**Issue by callahad** [mozilla-services/syncserver#42]
I left the port off my tokenServerURI, and got this totally unhelpful error.

![screen shot 2014-10-21 at 20 16 20](https://cloud.githubusercontent.com/assets/24193/4729768/562bb4c0-598d-11e4-87db-0f9726723e74.png)

We could totally be champions of the people if we fixed this upstream.

**Comment by rfk** [comment]
Going to close this ancient issue
