### ISSUE TITLE
Request: Update releases when major milestones are met

### ISSUE THREAD

**Issue by Fmstrat** [mozilla-services/syncserver#56]
Hi,

When running Auth/Sync servers in a production environment, it seems risky to me to be pulling from the master branch as per the instructions here: https://docs.services.mozilla.com/howtos/run-sync-1.5.html

As of this writing, the auth, content, and DB servers required all seem to have pretty commonly updated releases:
- Auth (8 releases, updated 4 days ago): https://github.com/mozilla/fxa-auth-server/releases
- Content (51 releases, updated 5 days ago): https://github.com/mozilla/fxa-content-server/releases
- Mysql: (4 releases, updated 6 days ago): https://github.com/mozilla/fxa-auth-db-mysql/releases

In contrast, the Sync server:
- Sync (2 releases, hasn't been updated in a year): https://github.com/mozilla-services/syncserver/releases

Any chance we could start seeing some 1.5.x releases?

Thanks.

**Comment by rfk** [comment]
Sure.  I just pushed a 1.5.1 tag.

FWIW, all of the FxA-related servers are under active development and are being deployed to production on a regular basis  The sync code is in maintenance-only mode, and we do not use this top-level repo for our own deployments, hence the lack of release tags.

**Comment by Fmstrat** [comment]
Great, thanks.
