### ISSUE TITLE
SSL errors while building under Debian

### ISSUE THREAD

**Issue by DRScheppler** [mozilla-services/syncserver#57]
Debian Version: 8.0
Kernel: 3.16.0.4-amd64
Python: 2.7.9
Openssl: 1.0.1k-3
Apache: 2.4.10-10
libapache2-mod-wsgi: 4.3.0-1

Configuration files:
syncserver.ini
https://pastebin.mozilla.org/8834612

sync.conf (/etc/apache2/sites-available)
https://pastebin.mozilla.org/8834613

Steps to reproduce:

git clone https://github.com/mozilla-services/syncserver /opt/syncserver/
cd /opt/syncserver
make build (successful)
make test (this passes)
systemctl restart apache2 (to re-load the syncserver wsgi)
/opt/syncserver/local/bin/python -m syncstorage.tests.functional.test_storage --use-token-server https://sync.example.com/token/1.0/sync/1.5 (This fails)

Error message in logs: (Full trace: https://pastebin.mozilla.org/8834611)

AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

Current resolution:
Upgrading requests to 2.7.0 - ./local/bin/pip install --upgrade requests

Possible long-term resolution:

Changing requests version in requirements.txt to 2.7.0

Hope this information helps

**Comment by rfk** [comment]
Thanks! Updated in https://github.com/mozilla-services/syncserver/commit/287bf190ec94eb5f52b9eaae4d6524f37f59a27d
