### ISSUE TITLE
Debian has a newer dependency on WebOb than Ubuntu; resulting in failed tests & refusal to run

### ISSUE THREAD

**Issue by canihavesomecoffee** [mozilla-services/syncserver#61]
Hello,

I'm trying to set up a syncserver using the [guide from docs.services.mozilla](https://docs.services.mozilla.com/howtos/run-sync-1.5.html), but for some unknown reason it keeps failing on me.

* `make build works` (gives warnings, but no errors)
* `make test` fails 3 tests: 
    * test_weird_args (syncstorage.tests.functional.test_old_storage.TestOldStorage)
    * test_overquota (syncstorage.tests.functional.test_storage.TestStorage)
    * test_weird_args (syncstorage.tests.functional.test_storage.TestStorage)
* trying to run the `make serve` results in a failure (return code 3). Running the `gunicorn` command manually results in no visible output (even with debug & logging on), and the is port unreachable.

The three tests  all fail with the same error (full traceback for one is available here: http://pastebin.com/iQhYwnTS):

```
 File "/home/user/syncserver/local/local/lib/python2.7/site-packages/webob/response.py", line 107, in __init__
    self.status = status
File "/home/user/syncserver/local/local/lib/python2.7/site-packages/webob/response.py", line 268, in _status__set
    raise ValueError('Invalid status code, integer required.')
ValueError: Invalid status code, integer required.
```

I've tested this on a RPi (Raspbian) & regular Debian Wheezy, and confirmed against an Ubuntu 14.04.

I've done a compare from the locally installed PIP packages and this is the result:

| Package | Debian version | Ubuntu version 14.04 LTS |
|-------------|--------------------|---------------------|
| WebOb   | 1.5.0b0            | 1.4.1                 |
| distribute | 0.6.24              | - |

Downgrading the WebOb version to 1.4.1 fixed the issue with the tests and the `make serve` command.

For future reference, this are the two commands needed to fix it:
```
./local/bin/pip uninstall WebOb
./local/bin/pip install WebOb==1.4.1
```

A suggestion to prevent this (rather obscure) error would be limiting the used pip version, or altering the code so that the 1.5 branch also would be supported.

I'll leave the issue open for now, so that it can be discussed if necessary.

**Comment by canihavesomecoffee** [comment]
I've done a bit of digging, and the problem would seem to be located somewhere in the httpexceptions.py class:

(Modified the response.py error to give the type & value)
'''
File "/home/user/syncserver/local/local/lib/python2.7/site-packages/webob/response.py", line 268, in _status__set
    raise ValueError('Invalid status code, integer required. Given type: %s, value: %s' % (type(value),value))
ValueError: Invalid status code, integer required. Given type: <type 'str'>, value: None None
''''

From what I can see the Response.init on line 209 from the httpexceptions has an unexisting parameter.

Could this be because Debian is using older/incompatible versions?

**Comment by canihavesomecoffee** [comment]
Update 3:

Downgrading the WebOb version to 1.4.1 fixed the issue.

For future reference, this are the two commands needed to fix it:
```
./local/bin/pip uninstall WebOb
./local/bin/pip install WebOb==1.4.1
```

I'll leave this issue open (but feel free to close it!), maybe a specific version can be used when installing the syncserver, or the incompability can be fixed?

**Comment by rfk** [comment]
Thanks for digging into this @canihavesomecoffee.  In https://github.com/mozilla-services/syncserver/commit/d65419ecfc7d29e85cf63f3f5eae62a57a901698 I added an explicit WebOb version to the requirements.txt, which will hopefully help.

Longer-term, this looks at first glance like an incompatibility between pyramid and newer versions of WebOb.  If you've got the time, it would be worth trying to upgrade pyramid to its latest version rather than the one pinned in requirements.txt, and see if that helps.

**Comment by canihavesomecoffee** [comment]
I ran some tests today on my RPi, and this is what I've found out:

The most recent versions of both the WebOb (1.5.0b0) and pyramid (1.6a2) are **incompatible** right now. However, there is a [fix](https://github.com/Pylons/pyramid/commit/88fcdc4e6a48f2646488565fbafd050f8e298ffa) in the current pyramid repo which will solve the errors once that hits pip (manually changing the `httpexceptions.py` fixes all test errors).

Summary:

| WebOb | Pyramid | Compatible? |
|-------------|---------------|----|
| 1.4.1 | 1.5 | Yes |
| 1.5.0b0             | 1.6a2 | **No** |
| 1.5.0b0 | GitHub | Yes |

I think that concludes this issue, as the incompatibility seems to be only temporary and is currently fixed by pinning the versions to the working combination.

**Comment by rfk** [comment]
Thanks so much for taking to time to dig into these details and report back here.
