### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by maikeldus** [mozilla-services/syncserver#63]
Tested on fresh Debian 8 machine, and the install worked fine after I installed g++. This is not mentioned in https://docs.services.mozilla.com/howtos/run-sync-1.5.html or the wiki page. It was not easy to find, so I guess it should be handy to include in the apt-get example?

**Comment by rfk** [comment]
Thanks for the heads-up, was it just an `apt-get install g++` that fixed the problem for you?

**Comment by maikeldus** [comment]
Yes.

**Comment by rfk** [comment]
thanks, added in https://github.com/mozilla-services/docs/commit/df9f84035915f48cf6f5f02d5f45fab8be56269b
