### ISSUE TITLE
Please consider update server-syncstorage dependency to 1.5.13

### ISSUE THREAD

**Issue by l-hedgehog** [mozilla-services/syncserver#66]
So that we can make Beijing office's sync stack compatible with Fx for iOS.

We might switch to use tokenserver and server-syncstorage instead of this repo in the future.

**Comment by rfk** [comment]
Thanks for the reminder, should be fixed in https://github.com/mozilla-services/syncserver/commit/150cef87457d226862fc831810c11ee9cf80bfb0

**Comment by l-hedgehog** [comment]
@rfk, thanks!
