### ISSUE TITLE
Synchronising addons might lead to data loss

### ISSUE THREAD

**Issue by godfuture** [mozilla-services/syncserver#77]
I have added multiple firefox desktop profiles to test syncing back and forth. It seems that the sync is working for history, passwords, bookmarks and tabs on desktop firefox clients. But not for settings. I will try to explain...

Many addons produces data as settings (e.g. [tab mix plus](https://addons.mozilla.org/de/firefox/addon/tab-mix-plus/)). In case a clean firefox desktop client is connected, addon settings seems to get lost and overwritten by its defaults. My guess is that the sync order of different modules might be problematic.

My assumption: Firefox settings get synced first, then the addon is synced (and installed), overwriting the addon settings with its defaults. The new defaults appear as latest changes and therefore get synced to server. Other clients sync the addon defaults and overwrite their existing ones. This should not happen!

If my assumption is correct then the issue could be fixed by changing the module sync order. In case there was a new addon added by sync, settings have to be synced after it. Maybe there is a restart required for installation. Then after this restart settings can be pulled from server. But this is just a guess...

This issue was also valid for Firefox Sync 1.1!

**Comment by rfk** [comment]
Thanks @godfuture - this sounds more like a sync client bug, and since those are tracked in bugzilla, I've taken the liberty of migrating it there and putting it in the right component:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1279405

Please add yourself to the bug in bugzilla if you'd like to follow along any progress on it.

**Comment by mhammond** [comment]
FTR, I closed that bug as invalid with the comment:

Most addons store their options in preferences, and while Sync does allow addons to "opt in" to syncing some of these preferences, most don't. Seeing preferences sync before addons, addons that use this facility work as expected (ie, their preferences are in place on the other device before the addon is installed.


So I can't see anything Sync can do here for these addons (but there is something the addons themselves could do)

Also, addons will soon be able to have an even better way of syncing their preferences via https://wiki.mozilla.org/WebExtensions/chrome.storage.sync
