### ISSUE TITLE
Meaning of "all-in-one package"

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [mozilla-services/syncserver#82]
Hi,
I am a little confused by the first paragraph of the Readme:

> This is an all-in-one package for running a self-hosted Firefox Sync server. If bundles the "tokenserver" project for authentication and the "syncstorage" project for storage, produce a single stand-alone webapp.

Does this mean this already includes the https://github.com/mozilla/fxa-auth-server and https://github.com/mozilla/fxa-content-server or will I still need to host them separately?

**Comment by rfk** [comment]
> will I still need to host them separately?

No, it only includes the various pieces necessary to run a sync storage server.  You can use it with the Mozilla-hosted accounts servers, or you can also host your own accounts servers as described at http://docs.services.mozilla.com/howtos/run-fxa.html
