### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by hemathor** [mozilla-services/syncserver#83]
i just tried to compile syncserver with 'make' and got the following error:

```
Compiling /tmp/pip-build-KWAxA_/gunicorn/gunicorn/workers/_gaiohttp.py ...
  File "/tmp/pip-build-KWAxA_/gunicorn/gunicorn/workers/_gaiohttp.py", line 64
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax
```

but for some reason, make seems to finish succesfully.
```
`Installed /home/hemathor/bin/syncserver
Processing dependencies for syncserver==1.5.2
Finished processing dependencies for syncserver==1.5.2
touch ./local/COMPLETE`
```
'make test' also finished without errors:
```
OK (skipped=4)
```
is the above error something i should worry about?

**Comment by rfk** [comment]
This is nothing to worry about, IIUC it's some optional python3.X support in the "gunicorn" package but doesn't break anything on older version of python.
