### ISSUE TITLE
MySQL utf8mb4 support

### ISSUE THREAD

**Issue by Mumrik17** [mozilla-services/syncserver#84]
I am using syncserver behind apache with mod_wsgi.
Lately, after having updated mysql to version 15.1, Distrib 10.1.21-MariaDB, ffsync stopped working.
I found the following log entries:

> File "/opt/syncserver/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 3066, in \_\_getitem__
return item.decode(self.charset)
LookupError: unknown encoding: utf8mb4

My setup:
Apache/2.4.25 (Unix)mod_wsgi/4.4.22 Python/2.7.13

I solved this by mapping the mysql encodings to their python alternatives like in [https://bitbucket.org/zzzeek/sqlalchemy/issues/2771/translate-utf8mb4-charset-when-detected](https://bitbucket.org/zzzeek/sqlalchemy/issues/2771/translate-utf8mb4-charset-when-detected).
So i changed line 3047 of syncserver/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py from `self.charset = charset` to `self.charset = self._encoding_compat.get(charset, charset)` and added     
```
_encoding_compat = {
        'koi8r': 'koi8_r',
        'koi8u': 'koi8_u',
        'ucs2': 'utf-16-be',  # can't be used as client connection encoding
        'utf16': 'utf-16-be',  # MySQL's uft16 is always bigendian
        'utf8mb4': 'utf8', # real utf8
        'eucjpms': 'ujis'
    }
```

in line 3050.
This way `self.charset` is set to utf8 instead of utf8mb4 and everything runs properly.
Is there a way to imlement this in sync server itself or am i facing a python problem?
Anyway, i hope this helps someone :)

**Comment by rfk** [comment]
Thanks @Mumrik17; I wonder if this caused by using using an older version of SQLAlchemy.  Could you please try upgrading SQLAlchemy like so and see if that helps?

```
 ./local/bin/pip install -U sqlalchemy pymysql
```

**Comment by Mumrik17** [comment]
Thanks @rfk - since SQLAlchemy was inside the virtual environment, the pip update didn't affect my copy of it. I tried cloning the repository again and setting `SQLAlchemy==0.9.4` to `SQLAlchemy==1.1.5` in line 7 of requirements.txt, then ran the makefile again. Now it works without cheating!

**Comment by rfk** [comment]
Thanks @Mumrik17; I've updated the dependencies in https://github.com/mozilla-services/syncserver/commit/0b784329b2c3246d66ebb565e50f2e4f6ebb1c79 so hopefully future users won't run into this issue.
