### ISSUE TITLE
Doc site is down

### ISSUE THREAD

**Issue by joshp23** [mozilla-services/syncserver#86]
I am attempting to deploy with some luck according to the README and some other instructions, however I am running into some issues and would like to refer to Mozilla's instructions for getting the sync AND identity server up and running. However, none of the doc links are working? 

Example:

> https://docs.services.mozilla.com/howtos/run-sync-1.5.html 

and all others yield a 403 forbidden error. Please advise.

**Comment by rfk** [comment]
Thanks for the report, we're tracking this issue over in https://bugzilla.mozilla.org/show_bug.cgi?id=1352469
