### ISSUE TITLE
Add config option for mysql connection pooling

### ISSUE THREAD

**Issue by derula** [mozilla-services/syncserver#87]
## Problem

A couple months ago, often my sync would fail because of aborted MySQL connections.

## Solution

As @rfk suggested to me, I lowered sqlkw["pool_recycle"] from 3600 to 120 in syncserver/staticnode.py. This seems to have fixed the issue to a degree where I haven't run into it in months. However, it would be nice to be able to configure this in the syncserver.ini.

## Side note

Thanks @rfk for your support on IRC :)

**Comment by rfk** [comment]
Thanks for filing this.  It should now be possible to specify this in config as of https://github.com/mozilla-services/syncserver/commit/8e693129e692766b9bf183a1fc955be7b560f581, using something like:

```
[tokenserver]
pool_recycle = 120
```

in your .ini file.
