### ISSUE TITLE
http vs https for public_url

### ISSUE THREAD

**Issue by rieje** [mozilla-services/syncserver#88]
This is a noob question and I apologize for asking it here, but irc link doesn't seem to work. The [doc](https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html) has the example for the setting `identity.sync.tokenserver.uri` with the value `http://sync.example.com/token/1.0/sync/1.5`. (The default setting uses the value `https://token.services.mozilla.com/1.0/sync/1.5`). 

Doesn't this mean the data that is synced between the server and the local machine is in cleartext if it's using http? What needs to be done to allow https data transfer?

Thanks.

P.S. Something like fail2ban shouldn't be necessary unless you're also hosting a Firefox Account server, right? The Sync server will only accept connections from an authenticated account? And how can I autostart the Sync server on boot (preferably via systemd service)?

**Comment by rfk** [comment]
> Doesn't this mean the data that is synced between the server and the local machine
> is in cleartext if it's using http?

It means the data is not encrypted for transport, yes.  But most of the data is encrypted by Firefox before it ever leaves your machine, so the impact would be less than you might think - someone snooping or intercepting that data, would be able to access the encrypted blobs you're storing on the server, but they wouldn't be able to access the actual sync data.

Nonetheless, https is a very good idea in practice, and it should "just work" if you run the server behind https with a valid certificate.  A typical setup would be to nginx running and accepting web traffic over https, forwarding it to the syncserver app locally, along the lines described in https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html#nginx-gunicorn

I should probably update the documentation to use a https URL by default...

> Something like fail2ban shouldn't be necessary unless you're also hosting a Firefox Account server, right?
> The Sync server will only accept connections from an authenticated account?

Right.

> And how can I autostart the Sync server on boot (preferably via systemd service)?

This third-party guide was written for the old sync server (named "server-full") but it's got a systemd example that should be straightforward to adapt to the syncserver codebase:

  https://tim.siosm.fr/blog/2012/12/11/firefox-sync-nginx-systemd/

**Comment by Jonny007-MKD** [comment]
I use uwsgi to run the server. This is my systemd file (copied from [here|https://uwsgi-docs.readthedocs.io/en/latest/Systemd.html]:

    [Unit]
    Description=Firefox Sync Server
    Documentation=https://moz-services-docs.readthedocs.io/en/latest/howtos/run-sync                                                                                                             -1.5.html
    
    [Service]
    User=firefoxsync
    Group=firefoxsync
    Type=notify
    ExecStart=/usr/bin/uwsgi --plugins python27 --manage-script-name --mount /=/home                                                                                                             /firefoxsync/syncserver/syncserver.wsgi --socket /home/firefoxsync/socket
    PrivateTmp=true
    Restart=on-failure
    KillSignal=SIGQUIT
    NotifyAccess=all
    StandardError=syslog
    
    [Install]
    WantedBy=multi-user.target

After stopping the service it is in failed state (because of SIGQUIT), but this is no problem for me.

**Comment by rfk** [comment]
It doesn't look like there's anything actionable left in this issue, so I'm going to close it out.
