### ISSUE TITLE
HTTP error 500

### ISSUE THREAD

**Issue by p0087** [mozilla-services/syncserver#94]
HTTP error 500 while getting https://github.com/mozilla-services/tokenserver/archive/1.2.27.zip

Cause: Commit https://github.com/mozilla-services/syncserver/commit/4f4787eadf729be5dd92d27b25c4317784ce00a7

**Comment by rfk** [comment]
Do you mean that you're able to fetch that file due to a HTTP 500 error?  I'm not able to reproduce, I wonder if it was an intermittent server problem on github.  Could you please try again and let me know if it's still happening?

**Comment by p0087** [comment]
Yep you're correct, was a temporary error (lasted 24 hrs for me so I thought it was something more). Worked fine just then. Will close
